import { WorkCategory, SupportedLanguage } from '../types';
import {
  HardHat,
  Package,
  Sparkles,
  Truck,
  Car,
  Boxes,
  Shield,
  Paintbrush,
  Wrench,
  Zap,
  Hammer,
  Building2,
  Trees,
  Utensils,
  Coffee,
  Ticket,
  Home,
  Briefcase,
  FileSpreadsheet,
  TrendingUp,
  Store,
  Navigation,
  Move,
  Cpu,
  Factory,
  Settings,
  Drill,
  Wheat,
  Tractor,
  Archive,
  HeartHandshake,
  Heart,
  HelpCircle,
} from 'lucide-react';
import React from 'react';

export interface CategoryInfo {
  id: WorkCategory;
  labels: Record<SupportedLanguage, string>;
  icon: React.ComponentType<{ size?: number; className?: string }>;
  color: string; // Tailwind color class for badge
  bgColor: string;
  borderColor: string;
  textColor: string;
  defaultImage: string;
  defaultWage: number;
  defaultTitle: string;
  defaultDescription: string;
}

export const WORK_CATEGORIES: CategoryInfo[] = [
  {
    id: 'Construction',
    labels: { en: 'Construction', te: 'భవన నిర్మాణం', hi: 'भवन निर्माण', ta: 'கட்டுமானம்' },
    icon: HardHat,
    color: 'amber',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-700',
    defaultImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    defaultWage: 850,
    defaultTitle: 'Construction Site Helper',
    defaultDescription: 'Need workers for brick moving, site clearance, and cement mixing assistance.',
  },
  {
    id: 'Loading/Unloading',
    labels: { en: 'Loading/Unloading', te: 'లోడింగ్ / అన్‌లోడింగ్', hi: 'लोडिंग / अनलोडिंग', ta: 'ஏற்றுதல் / இறக்குதல்' },
    icon: Package,
    color: 'blue',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-blue-700',
    defaultImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    defaultWage: 800,
    defaultTitle: 'Warehouse Loading & Sorting Helper',
    defaultDescription: 'Need energetic helpers for unloading cartons, sorting dry food boxes, and arranging storeroom racks.',
  },
  {
    id: 'Cleaning',
    labels: { en: 'Cleaning', te: 'క్లీనింగ్ & పరిశుభ్రత', hi: 'सफाई एवं स्वच्छता', ta: 'சுத்தம் செய்தல்' },
    icon: Sparkles,
    color: 'emerald',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-700',
    defaultImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    defaultWage: 650,
    defaultTitle: 'Deep Cleaning Specialist',
    defaultDescription: 'Cleaning helper needed for commercial premises floor scrubbing, window wiping, and trash disposal.',
  },
  {
    id: 'Delivery',
    labels: { en: 'Delivery', te: 'డెలివరీ', hi: 'डिलीवरी', ta: 'டெலிவரி' },
    icon: Truck,
    color: 'sky',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-200',
    textColor: 'text-sky-700',
    defaultImage: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&auto=format&fit=crop&q=80',
    defaultWage: 750,
    defaultTitle: 'Express Delivery Partner',
    defaultDescription: 'Local grocery/parcel delivery for 15-20 local drop points within a 5 km radius.',
  },
  {
    id: 'Driving',
    labels: { en: 'Driving', te: 'డ్రైవింగ్', hi: 'ड्राइविंग', ta: 'ஓட்டுநர்' },
    icon: Car,
    color: 'indigo',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    textColor: 'text-indigo-700',
    defaultImage: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&auto=format&fit=crop&q=80',
    defaultWage: 900,
    defaultTitle: 'Commercial Vehicle Driver',
    defaultDescription: 'Experienced driver with valid license for local delivery van and commercial pick-up runs.',
  },
  {
    id: 'Warehouse',
    labels: { en: 'Warehouse', te: 'వేర్‌హౌస్ & గోడౌన్', hi: 'गोदाम / वेयरहाउस', ta: 'கிடங்கு' },
    icon: Boxes,
    color: 'violet',
    bgColor: 'bg-violet-50',
    borderColor: 'border-violet-200',
    textColor: 'text-violet-700',
    defaultImage: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&auto=format&fit=crop&q=80',
    defaultWage: 750,
    defaultTitle: 'Warehouse Inventory Helper',
    defaultDescription: 'Inventory scanning, carton stacking, and picking items for outgoing dispatch.',
  },
  {
    id: 'Security',
    labels: { en: 'Security', te: 'సెక్యూరిటీ గార్డ్', hi: 'सुरक्षा गार्ड', ta: 'பாதுகாவலர்' },
    icon: Shield,
    color: 'slate',
    bgColor: 'bg-slate-100',
    borderColor: 'border-slate-300',
    textColor: 'text-slate-800',
    defaultImage: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&auto=format&fit=crop&q=80',
    defaultWage: 800,
    defaultTitle: 'Day Shift Security Guard',
    defaultDescription: 'Gate visitor check-in, parking control, and entry register maintenance for retail store.',
  },
  {
    id: 'Painting',
    labels: { en: 'Painting', te: 'పెయింటింగ్', hi: 'पेंटिंग', ta: 'வண்ணம் தீட்டுதல்' },
    icon: Paintbrush,
    color: 'rose',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-200',
    textColor: 'text-rose-700',
    defaultImage: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
    defaultWage: 850,
    defaultTitle: 'Interior Wall Painter Helper',
    defaultDescription: 'Surface putty application, primer rolling, and room wall touch-ups.',
  },
  {
    id: 'Plumbing',
    labels: { en: 'Plumbing', te: 'ప్లంబింగ్', hi: 'प्लंबिंग', ta: 'பிளம்பிங்' },
    icon: Wrench,
    color: 'cyan',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-200',
    textColor: 'text-cyan-700',
    defaultImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
    defaultWage: 850,
    defaultTitle: 'Plumbing Pipe Fitting Assistant',
    defaultDescription: 'Assisting in pipe cutting, drain cleaning, and tap valve replacement.',
  },
  {
    id: 'Electrical Work',
    labels: { en: 'Electrical Work', te: 'ఎలక్ట్రికల్ పనులు', hi: 'इलेक्ट्रिकल काम', ta: 'மின்சார வேலை' },
    icon: Zap,
    color: 'yellow',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-200',
    textColor: 'text-yellow-800',
    defaultImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
    defaultWage: 900,
    defaultTitle: 'Electrical Wiring Assistant',
    defaultDescription: 'Conduit laying, switchboard fitting, and light fixture installation support.',
  },
  {
    id: 'Carpentry',
    labels: { en: 'Carpentry', te: 'వడ్రంగి / కార్పెంట్రీ', hi: 'बढ़ई का काम', ta: 'மரவேலை' },
    icon: Hammer,
    color: 'orange',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-orange-800',
    defaultImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&auto=format&fit=crop&q=80',
    defaultWage: 850,
    defaultTitle: 'Furniture Assembly & Woodwork',
    defaultDescription: 'Wood cutting, door hinge fixing, and modular furniture assembly.',
  },
  {
    id: 'Masonry',
    labels: { en: 'Masonry', te: 'తాపీ పని / మేస్త్రీ', hi: 'राजमिस्त्री का काम', ta: 'கொத்து வேலை' },
    icon: Building2,
    color: 'stone',
    bgColor: 'bg-stone-100',
    borderColor: 'border-stone-300',
    textColor: 'text-stone-800',
    defaultImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
    defaultWage: 900,
    defaultTitle: 'Masonry & Plastering Work',
    defaultDescription: 'Bricklaying, wall plastering, and floor tiling helper needed.',
  },
  {
    id: 'Gardening',
    labels: { en: 'Gardening', te: 'గార్డెనింగ్ & తోటపని', hi: 'बागवानी', ta: 'தோட்டக்கலை' },
    icon: Trees,
    color: 'green',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-700',
    defaultImage: 'https://images.unsplash.com/photo-1558904541-efa8c4a08931?w=800&auto=format&fit=crop&q=80',
    defaultWage: 650,
    defaultTitle: 'Garden Maintenance Helper',
    defaultDescription: 'Lawn mowing, flower bed weeding, soil tilling, and hedge trimming.',
  },
  {
    id: 'Cooking',
    labels: { en: 'Cooking', te: 'వంట పని', hi: 'रसोई / खाना बनाना', ta: 'சமையல்' },
    icon: Utensils,
    color: 'red',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-700',
    defaultImage: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&auto=format&fit=crop&q=80',
    defaultWage: 750,
    defaultTitle: 'Kitchen Prep & Cooking Assistant',
    defaultDescription: 'Vegetable cutting, prep station management, and assistance for bulk catering.',
  },
  {
    id: 'Hotel/Restaurant',
    labels: { en: 'Hotel / Restaurant', te: 'హోటల్ & రెస్టారెంట్', hi: 'होटल / रेस्टोरेंट', ta: 'ஹோட்டல் / உணவகம்' },
    icon: Coffee,
    color: 'amber',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-800',
    defaultImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'Restaurant Steward & Helper',
    defaultDescription: 'Table setup, plate clearing, and dining floor assistance during peak shift.',
  },
  {
    id: 'Event Staff',
    labels: { en: 'Event Staff', te: 'ఈవెంట్ స్టాఫ్', hi: 'इवेंट स्टाफ', ta: 'நிகழ்ச்சி ஊழியர்கள்' },
    icon: Ticket,
    color: 'purple',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-200',
    textColor: 'text-purple-700',
    defaultImage: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop&q=80',
    defaultWage: 800,
    defaultTitle: 'Event Stage & Guest Coordination',
    defaultDescription: 'Event setup, guest assistance, banner installation, and logistics coordination.',
  },
  {
    id: 'Housekeeping',
    labels: { en: 'Housekeeping', te: 'హౌస్‌కీపింగ్', hi: 'हाउसकीपिंग', ta: 'இல்லப் பராமரிப்பு' },
    icon: Home,
    color: 'teal',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-200',
    textColor: 'text-teal-700',
    defaultImage: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=800&auto=format&fit=crop&q=80',
    defaultWage: 650,
    defaultTitle: 'Hospitality Housekeeping Staff',
    defaultDescription: 'Linen changing, room tidying, and washroom sanitation.',
  },
  {
    id: 'Office Assistant',
    labels: { en: 'Office Assistant', te: 'ఆఫీస్ అసిస్టెంట్', hi: 'कार्यालय सहायक', ta: 'அலுவலக உதவியாளர்' },
    icon: Briefcase,
    color: 'blue',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-blue-700',
    defaultImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'Office Attendant & Runner',
    defaultDescription: 'Filing, courier receipt, beverage service, and local office errand support.',
  },
  {
    id: 'Data Entry',
    labels: { en: 'Data Entry', te: 'డేటా ఎంట్రీ', hi: 'डेटा एंट्री', ta: 'தரவு உள்ளீடு' },
    icon: FileSpreadsheet,
    color: 'emerald',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-700',
    defaultImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'Invoice & Excel Data Entry',
    defaultDescription: 'Entering paper receipts, updating customer lists in spreadsheets accurately.',
  },
  {
    id: 'Sales',
    labels: { en: 'Sales', te: 'సేల్స్ ప్రమోషన్', hi: 'बिक्री / सेल्स', ta: 'விற்பனை' },
    icon: TrendingUp,
    color: 'lime',
    bgColor: 'bg-lime-50',
    borderColor: 'border-lime-200',
    textColor: 'text-lime-800',
    defaultImage: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?w=800&auto=format&fit=crop&q=80',
    defaultWage: 750,
    defaultTitle: 'In-Store Sales Promoter',
    defaultDescription: 'Showcasing product samples and assisting retail customers with product info.',
  },
  {
    id: 'Retail',
    labels: { en: 'Retail', te: 'రిటైల్ స్టోర్ హెల్పర్', hi: 'रिटेल स्टोर स्टाफ', ta: 'சில்லறை விற்பனை' },
    icon: Store,
    color: 'pink',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-200',
    textColor: 'text-pink-700',
    defaultImage: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'Retail Shelf Merchandiser',
    defaultDescription: 'Stocking store shelves, price tag verification, and counter bagging.',
  },
  {
    id: 'Delivery Partner',
    labels: { en: 'Delivery Partner', te: 'డెలివరీ పార్ట్‌నర్', hi: 'डिलीवरी पार्टनर', ta: 'டெலிவரி பார்ட்னர்' },
    icon: Navigation,
    color: 'sky',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-200',
    textColor: 'text-sky-700',
    defaultImage: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&auto=format&fit=crop&q=80',
    defaultWage: 800,
    defaultTitle: 'Two-Wheeler Delivery Associate',
    defaultDescription: 'Two-wheeler parcel dispatch across assigned city zone. Fuel bonus included.',
  },
  {
    id: 'Moving/Shifting',
    labels: { en: 'Moving / Shifting', te: 'ఇల్లు & ఆఫీస్ మార్పిడి', hi: 'स्थानांतरण / शिफ्टिंग', ta: 'இடமாற்றம்' },
    icon: Move,
    color: 'amber',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-800',
    defaultImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    defaultWage: 850,
    defaultTitle: 'Home Relocation Helper',
    defaultDescription: 'Safe lifting of furniture, mattress loading, and fragile bubble wrapping.',
  },
  {
    id: 'Machine Operator',
    labels: { en: 'Machine Operator', te: 'మెషిన్ ఆపరేటర్', hi: 'मशीन ऑपरेटर', ta: 'இயந்திர ஆபரேட்டர்' },
    icon: Cpu,
    color: 'indigo',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    textColor: 'text-indigo-700',
    defaultImage: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    defaultWage: 950,
    defaultTitle: 'Packaging Machine Operator',
    defaultDescription: 'Operating semi-automatic sealing and labeling machine on factory line.',
  },
  {
    id: 'Factory Worker',
    labels: { en: 'Factory Worker', te: 'ఫ్యాక్టరీ వర్కర్', hi: 'कारखाना कामगार', ta: 'தொழிற்சாலை ஊழியர்' },
    icon: Factory,
    color: 'zinc',
    bgColor: 'bg-zinc-100',
    borderColor: 'border-zinc-300',
    textColor: 'text-zinc-800',
    defaultImage: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80',
    defaultWage: 750,
    defaultTitle: 'Assembly Line Factory Worker',
    defaultDescription: 'Light manufacturing, component assembly, and quality checking.',
  },
  {
    id: 'Maintenance',
    labels: { en: 'Maintenance', te: 'మెయింటెనెన్స్', hi: 'रखरखाव / मेंटेनेंस', ta: 'பராமரிப்பு' },
    icon: Settings,
    color: 'slate',
    bgColor: 'bg-slate-100',
    borderColor: 'border-slate-300',
    textColor: 'text-slate-800',
    defaultImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    defaultWage: 800,
    defaultTitle: 'Facility Maintenance Assistant',
    defaultDescription: 'General building upkeep, filter cleaning, minor touch-ups.',
  },
  {
    id: 'Repair',
    labels: { en: 'Repair', te: 'రిపేర్ & సర్వీస్', hi: 'मरम्मत सेवा', ta: 'பழுதுபார்ப்பு' },
    icon: Drill,
    color: 'orange',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-orange-700',
    defaultImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    defaultWage: 800,
    defaultTitle: 'General Appliance & Fixture Repair',
    defaultDescription: 'Drilling, wall mounting, fan fixing, and lock repair assistance.',
  },
  {
    id: 'Agriculture',
    labels: { en: 'Agriculture', te: 'వ్యవసాయ పనులు', hi: 'कृषि कार्य', ta: 'விவசாயம்' },
    icon: Wheat,
    color: 'emerald',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-700',
    defaultImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80',
    defaultWage: 650,
    defaultTitle: 'Farm Field Assistant',
    defaultDescription: 'Assisting with crop harvesting, weeding, and seed bed preparation.',
  },
  {
    id: 'Farm Work',
    labels: { en: 'Farm Work', te: 'పొలం పనులు', hi: 'खेत का काम', ta: 'பண்ணை வேலை' },
    icon: Tractor,
    color: 'green',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-green-800',
    defaultImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=800&auto=format&fit=crop&q=80',
    defaultWage: 650,
    defaultTitle: 'Livestock & Farm Hand',
    defaultDescription: 'Cattle feeding, dairy shed cleaning, and farm produce crate loading.',
  },
  {
    id: 'Packing',
    labels: { en: 'Packing', te: 'ప్యాకింగ్ & బాక్సింగ్', hi: 'पैकिंग / पैकेजिंग', ta: 'பேக்கிங்' },
    icon: Archive,
    color: 'yellow',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-200',
    textColor: 'text-yellow-800',
    defaultImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'Goods Packaging Specialist',
    defaultDescription: 'Polybag sealing, bubble wrapping, barcode tagging, and gift box assembly.',
  },
  {
    id: 'Domestic Help',
    labels: { en: 'Domestic Help', te: 'ఇంటి సహాయకుడు', hi: 'घरेलू कामगार', ta: 'வீட்டு வேலை' },
    icon: HeartHandshake,
    color: 'teal',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-200',
    textColor: 'text-teal-700',
    defaultImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    defaultWage: 600,
    defaultTitle: 'Domestic Helper & Cleaner',
    defaultDescription: 'Utensil washing, kitchen tidying, and dusting for family home.',
  },
  {
    id: 'Caregiving',
    labels: { en: 'Caregiving', te: 'కేర్‌గివింగ్ & సంరక్షణ', hi: 'देखभाल / केयरगिविंग', ta: 'பராமரிப்பாளர்' },
    icon: Heart,
    color: 'rose',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-200',
    textColor: 'text-rose-700',
    defaultImage: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    defaultWage: 850,
    defaultTitle: 'Elderly Assistance Attendant',
    defaultDescription: 'Companion support, medicine reminders, and mobility assistance.',
  },
  {
    id: 'Labour',
    labels: { en: 'General Labour', te: 'సాధారణ శ్రామికుడు', hi: 'सामान्य श्रम', ta: 'பொது தொழிலாளி' },
    icon: Hammer,
    color: 'blue',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-blue-700',
    defaultImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'General Physical Labour',
    defaultDescription: 'Material shifting, debris clearing, and manual assistance.',
  },
  {
    id: 'Shop/Store Help',
    labels: { en: 'Shop / Store Help', te: 'దుకాణం సహాయకుడు', hi: 'दुकान सहायक', ta: 'கடை உதவியாளர்' },
    icon: Store,
    color: 'emerald',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-700',
    defaultImage: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&auto=format&fit=crop&q=80',
    defaultWage: 650,
    defaultTitle: 'Grocery Store Counter Helper',
    defaultDescription: 'Customer order packaging, grocery bag packing, and shelf restock.',
  },
  {
    id: 'Other',
    labels: { en: 'Other Work', te: 'ఇతర పనులు', hi: 'अन्य कार्य', ta: 'மற்றவை' },
    icon: HelpCircle,
    color: 'slate',
    bgColor: 'bg-slate-100',
    borderColor: 'border-slate-300',
    textColor: 'text-slate-800',
    defaultImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    defaultWage: 700,
    defaultTitle: 'General Gig Assistant',
    defaultDescription: 'Custom daily gig task as specified by employer.',
  },
];

export function getCategoryInfo(id: WorkCategory): CategoryInfo {
  return WORK_CATEGORIES.find(c => c.id === id) || WORK_CATEGORIES[WORK_CATEGORIES.length - 1];
}

export function getCategoryLabel(id: WorkCategory, lang: SupportedLanguage): string {
  const info = getCategoryInfo(id);
  return info.labels[lang] || info.labels.en || id;
}

